package stripeHandler

const (
    PRODUCTION_MODE = false
    PUBLISHABLE_KEY_STAGING = "pk_test_51NDJySI8t6lPUIZhP6TevYxPDeaLNxPRRv2BolNbnYJeZssBUXNTIJkUMRPIo5O5bAKqrgCsawixvTy1Aj53jgDN00y9IbQ6NI"
    PUBLISHABLE_KEY_PRODUCTION = "*******"
    SECRET_KEY_STAGING = "sk_test_51NDJySI8t6lPUIZhPu7tsA95IE5Namq3HW8vcrIXYglw7gX2h2qw1UVq8PtjthepIYEbPOsloZt4GZM8DIlKoIiA00yADe8vHr"
    SECRET_KEY_PRODUCTION = "*******"

)